import csv
from pathlib import Path


def export_csv_findings(findings, output_file):
    csv_path = output_file.replace(".json", ".csv")

    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)

        writer.writerow(
            ["Severity", "Subdomain", "Score", "Reasons"]
        )

        for item in findings:
            writer.writerow(
                [
                    item["severity"],
                    item["subdomain"],
                    item["score"],
                    "; ".join(item["reasons"]),
                ]
            )

    return csv_path


def export_html_report(
    domain,
    findings,
    output_file,
    resolved_assets,
):
    html_path = output_file.replace(".json", ".html")

    rows = ""

    for item in findings:
        if item["severity"] == "INFO":
            continue

        rows += f"""
        <tr>
            <td>{item['severity']}</td>
            <td>{item['subdomain']}</td>
            <td>{item['score']}</td>
            <td>{'<br>'.join(item['reasons'])}</td>
        </tr>
        """

    html = f"""
    <html>
    <head>
        <title>CySentra ASM Report</title>
        <style>
            body {{ font-family: Arial; margin:40px; }}
            table {{ border-collapse: collapse; width:100%; }}
            th, td {{ border:1px solid #ccc; padding:8px; text-align:left; }}
            th {{ background:#eee; }}
            h1 {{ color:#222; }}
        </style>
    </head>
    <body>

    <h1>CySentra ASM Security Report</h1>

    <p><b>Target:</b> {domain}</p>
    <p><b>Resolved Assets:</b> {resolved_assets}</p>
    <p><b>Generated By:</b> CySentra ASM</p>

    <h2>Risk Findings</h2>

    <table>
        <tr>
            <th>Severity</th>
            <th>Subdomain</th>
            <th>Score</th>
            <th>Reasons</th>
        </tr>
        {rows}
    </table>

    </body>
    </html>
    """

    Path(html_path).write_text(html, encoding="utf-8")

    return html_path
